#import "@preview/lilaq:0.6.0" as lq

// Generated by generate-lilaq.py
// One figure per file size; each box is one benchmark configuration.
// GET latency — tiny — cache=warm
#figure(
  lq.diagram(
    width: 10cm,
    height: 10cm,
    title: [GET latency — tiny — cache=warm],
    xaxis: (ticks: ((1, [S3 Direct]), (2, [OSWS]), (3, [No file cache]), (4, [No encryption]))),
    ylabel: [Latency (ms)],
    yscale: "log",
    lq.boxplot(
      x: 1,
      (
        median:       11.15,
        q1:           10.44,
        q3:           12.39,
        whisker-low:  9.34,
        whisker-high: 14.37,
        outliers:     (16.17,),
      ),
    ),
    lq.boxplot(
      x: 2,
      (
        median:       29.18,
        q1:           28.04,
        q3:           30.87,
        whisker-low:  24.77,
        whisker-high: 31.76,
        outliers:     (36.71,),
      ),
    ),
    lq.boxplot(
      x: 3,
      (
        median:       34.42,
        q1:           32.84,
        q3:           35.43,
        whisker-low:  31.41,
        whisker-high: 36.87,
        outliers:     (42.39,),
      ),
    ),
    lq.boxplot(
      x: 4,
      (
        median:       35.54,
        q1:           34.22,
        q3:           39.10,
        whisker-low:  33.48,
        whisker-high: 42.54,
        outliers:     (50.55,),
      ),
    ),
  ),
  caption: [GET latency — tiny — cache=warm],
)

// GET latency — small — cache=warm
#figure(
  lq.diagram(
    width: 10cm,
    height: 10cm,
    title: [GET latency — small — cache=warm],
    xaxis: (ticks: ((1, [S3 Direct]), (2, [OSWS]), (3, [No file cache]), (4, [No encryption]))),
    ylabel: [Latency (ms)],
    yscale: "log",
    lq.boxplot(
      x: 1,
      (
        median:       32.69,
        q1:           31.92,
        q3:           33.85,
        whisker-low:  30.31,
        whisker-high: 34.70,
        outliers:     (27.89, 40.82,),
      ),
    ),
    lq.boxplot(
      x: 2,
      (
        median:       81.64,
        q1:           78.39,
        q3:           85.61,
        whisker-low:  72.33,
        whisker-high: 91.87,
        outliers:     (),
      ),
    ),
    lq.boxplot(
      x: 3,
      (
        median:       129.18,
        q1:           122.53,
        q3:           132.63,
        whisker-low:  117.04,
        whisker-high: 137.57,
        outliers:     (151.47,),
      ),
    ),
    lq.boxplot(
      x: 4,
      (
        median:       132.89,
        q1:           130.37,
        q3:           143.71,
        whisker-low:  114.63,
        whisker-high: 146.32,
        outliers:     (165.35, 167.38,),
      ),
    ),
  ),
  caption: [GET latency — small — cache=warm],
)

// GET latency — medium — cache=warm
#figure(
  lq.diagram(
    width: 10cm,
    height: 10cm,
    title: [GET latency — medium — cache=warm],
    xaxis: (ticks: ((1, [S3 Direct]), (2, [OSWS]), (3, [No file cache]), (4, [No encryption]))),
    ylabel: [Latency (ms)],
    yscale: "log",
    lq.boxplot(
      x: 1,
      (
        median:       489.84,
        q1:           446.43,
        q3:           492.42,
        whisker-low:  407.31,
        whisker-high: 555.38,
        outliers:     (),
      ),
    ),
    lq.boxplot(
      x: 2,
      (
        median:       1616.59,
        q1:           1516.91,
        q3:           1672.45,
        whisker-low:  1449.78,
        whisker-high: 1769.42,
        outliers:     (),
      ),
    ),
    lq.boxplot(
      x: 3,
      (
        median:       2281.57,
        q1:           2266.44,
        q3:           2292.01,
        whisker-low:  2262.00,
        whisker-high: 2292.24,
        outliers:     (2226.53, 2391.55, 2419.30,),
      ),
    ),
    lq.boxplot(
      x: 4,
      (
        median:       1302.23,
        q1:           1287.45,
        q3:           1319.30,
        whisker-low:  1277.23,
        whisker-high: 1348.11,
        outliers:     (1205.95, 1378.10,),
      ),
    ),
  ),
  caption: [GET latency — medium — cache=warm],
)

// GET latency — large — cache=warm
#figure(
  lq.diagram(
    width: 10cm,
    height: 10cm,
    title: [GET latency — large — cache=warm],
    xaxis: (ticks: ((1, [S3 Direct]), (2, [OSWS]), (3, [No file cache]), (4, [No encryption]))),
    ylabel: [Latency (ms)],
    yscale: "log",
    
    lq.boxplot(
      x: 1,
      (
        median:       1915.01,
        q1:           1788.41,
        q3:           1970.23,
        whisker-low:  1694.40,
        whisker-high: 2014.81,
        outliers:     (),
      ),
    ),
    lq.boxplot(
      x: 2,
      (
        median:       6097.30,
        q1:           5870.91,
        q3:           6222.73,
        whisker-low:  5560.07,
        whisker-high: 6361.81,
        outliers:     (),
      ),
    ),
    lq.boxplot(
      x: 3,
      (
        median:       9024.56,
        q1:           8937.16,
        q3:           9105.53,
        whisker-low:  8690.16,
        whisker-high: 9130.78,
        outliers:     (9570.17, 9610.25,),
      ),
    ),
    lq.boxplot(
      x: 4,
      (
        median:       5103.12,
        q1:           4961.36,
        q3:           5457.66,
        whisker-low:  4923.45,
        whisker-high: 5742.45,
        outliers:     (),
      ),
    ),
  ),
  caption: [GET latency — large — cache=warm],
)
