#import "@preview/lilaq:0.6.0" as lq

// Generated by generate-thesis-plots.py
// Impact of DEK caching on cold GET latency
#figure(
  lq.diagram(
    width: 10cm,
    title: [Impact of DEK caching on cold GET latency],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]))),
    ylabel: [Latency (ms)],
    yscale: "log",
  lq.plot(
    (1.00, 2.00, 3.00),
    (3558.46, 3702.97, 6024.01),
    mark: "o",
    label: [DEK cache enabled],
  ),
  lq.plot(
    (1.00, 2.00, 3.00),
    (20093.96, 15857.88, 78966.21),
    mark: "s",
    label: [DEK cache disabled],
  ),
  ),
  caption: [Cold GET latency with and without the in-memory DEK cache (tiny--medium only; large timed out on most runs without DEK caching). Without the cache, every GET fetches all column DEKs from Azure Key Vault sequentially, compounding with the cold file access cost.],
)

// Cold GET latency: encryption vs no encryption
#figure(
  lq.diagram(
    width: 10cm,
    title: [Cold GET latency: encryption vs no encryption],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]), (4, [large]))),
    ylabel: [Latency (ms)],
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (3558.46, 3702.97, 6024.01, 13230.02),
    mark: "o",
    label: [OSWS (encrypted)],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (38.27, 152.75, 1300.25, 5015.99),
    mark: "s",
    label: [OSWS (no encrypt)],
  ),
  ),
  caption: [Cold GET on a linear scale. The encrypted path stays nearly flat at ~3.5 s for tiny and small, reflecting ~50 sequential Azure Key Vault round-trips (~70 ms each) regardless of file size. The unencrypted path scales with data size from the start.],
)

// Impact of file caching on warm GET latency
#figure(
  lq.diagram(
    width: 10cm,
    title: [Impact of file caching on warm GET latency],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]), (4, [large]))),
    ylabel: [Latency (ms)],
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (29.18, 81.64, 1616.59, 6097.30),
    mark: "o",
    label: [File cache enabled],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (34.42, 129.18, 2281.57, 9024.56),
    mark: "s",
    label: [File cache disabled],
  ),
  ),
  caption: [Warm GET with and without the decrypted-file cache. The benefit is modest for small files but grows with file size as the cost of re-decryption becomes the dominant factor.],
)

// Warm GET latency: cost layers
#figure(
  lq.diagram(
    width: 10cm,
    title: [Warm GET latency: cost layers],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]), (4, [large]))),
    ylabel: [Latency (ms)],
    yscale: "log",
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (11.15, 32.69, 489.84, 1915.01),
    mark: "o",
    color: rgb("#94a4a2"),
    label: [S3 Direct],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (35.54, 132.89, 1302.23, 5103.12),
    mark: "s",
    color: rgb("#ffa90e"),
    label: [OSWS (no encrypt)],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (29.18, 81.64, 1616.59, 6097.30),
    mark: "^",
    color: rgb("#3f90da"),
    label: [OSWS (encrypted)],
  ),
  ),
  caption: [Warm GET across three configurations. S3 Direct is the raw baseline. OSWS without encryption adds proxy and Parquet column-reconstruction overhead. OSWS with encryption adds decryption on top of that.],
)
