#import "../cmds.typ": todo
#figure(
  caption: [Admin role management endpoints provided by OSWS],
  table(
    columns: 3,
    align: left + horizon,
    [*Method*], [*Path*], [*Description*],
    [GET],
      [`/api/admin/columns`],
      [Get all columns],
    [POST],
      [`/api/admin/columns/{columnId}/roles/{roleId}`],
      [Grant access on column with ID `columnId`to role with id `roleId`],
    [DELETE],
      [`/api/admin/columns/{columnId}/roles/{roleId}`],
      [Revoke access on column with ID `columnId` to role with ID `roleId`],
    [GET],
      [`/api/admin/roles`],
      [Get all roles],
    [POST],
      [`/api/admin/roles`],
      [Create a role],
    [DELETE],
      [`/api/admin/roles/{id}`],
      [Delete role with ID `id`],
    [POST],
      [`/api/admin/roles/{parentId}/inherit/{childId}`],
      [Make role with ID `parentId` inherit role with ID `childId`],
    [DELETE],
      [`/api/admin/roles/{parentId}/inherit/{childId}`],
      [Delete inheritance of role `parentId` from role `childId`],
    [GET],
      [`/api/admin/users`],
      [Get all users],
    [POST],
      [`/api/admin/users/{userId}/roles/{roleId}`],
      [Grant role with ID `roleId` to user with ID `userId`],
    [DELETE],
      [`/api/admin/users/{userId}/roles/{roleId}`],
      [Revoke role with ID `roleId` from user with ID `userId`],
  ),
)<tab:admin-endpoints>
