#import "../cmds.typ": todo
#figure(
  caption: [S3-Compatible endpoints provided by OSWS],
  table(
    columns: 3,
    align: left + horizon,
    [*Method*], [*Path*], [*Description*],
    [Get],
      [`/api/admin/columns`],
      [Get columns #todo[given something]],
    [Post],
      [`/api/admin/columns/{columnId}/roles/{roleId}`],
      [#todo[todo]],
    [Delete],
      [`/api/admin/columns/{columnId}/roles/{roleId}`],
      [#todo[todo]],
    [Post],
      [`/api/admin/roles/{id}`],
      [Create an RBAC role],
    [Delete],
      [`/api/admin/roles/{id}`],
      [Delete an RBAC role],
    [Post],
      [`/api/admin/roles/{parentId}/inherit/{childId}`],
      [Make an RBAC role inherit another RBAC role],
    [Delete],
      [`/api/admin/roles/{parentId}/inherit/{childId}`],
      [Delete an RBAC role inheriting another RBAC role],
    [Get],
      [`/api/admin/users`],
      [#todo[todo]],
    [Post],
      [`/api/admin/users/{userId}/roles/{roleId}`],
      [#todo[todo]],
    [Delete],
      [`/api/admin/users/{userId}/roles/{roleId}`],
      [#todo[todo]],
  ),
)<tab:admin-endpoints>
