#figure(
  caption: [Application endpoints provided by OSWS for web frontend],
  table(
    columns: 3,
    align: left + horizon,
    [*Method*], [*Path*], [*Description*],
    [GET],
      [`/api/me`],
      [Current user profile (triggers JIT provisioning)],
    [GET],
      [`/api/credentials`],
      [List the user's S3 credentials],
    [POST],
      [`/api/credentials`],
      [Create a new S3 credential (access key + secret key)],
    [DELETE],
      [`/api/credentials/{id}`],
      [Revoke a credential (soft delete)],
  ),
)<tab:applications-endpoints>
