#figure(
  caption: [S3-Compatible endpoints provided by OSWS],
  table(
    columns: 3,
    align: left + horizon,
    [*Method*], [*Path*], [*Description*],
    [GET],
      [`/`],
      [List buckets],
    [GET],
      [`/{bucket}`],
      [List objects in a bucket],
    [PUT],
      [`/{bucket}`],
      [Create bucket],
    [DELETE],
      [`/{bucket}`],
      [Delete bucket],
     [POST],
      [`/{bucket}?delete`],
      [Delete multiple objects in bucket],
    [HEAD],
      [`/{bucket}`],
      [Retrieve bucket metadata],
    [HEAD],
      [`/{bucket}/{key}`],
      [Retrieve object metadata],
    [GET],
      [`/bucket}/{*key}`],
      [Retrieve an object (with decryption and column filtering for Parquet)],
    [PUT],
      [`/{bucket}/{*key}`],
      [Store an object (with encryption for Parquet)],
    [DELETE],
      [`/{bucket}/{*key}`],
      [Delete an object],
  ),
)<tab:s3-compatible-endpoints>

