#figure(
  caption: [S3-Compatible endpoints provided by OSWS],
  table(
    columns: 3,
    align: left + horizon,
    [*Method*], [*Path*], [*Description*],
    [Get],
      [`/`],
      [List buckets],
    [Get],
      [`/{bucket}`],
      [List objects in a bucket],
    [Put],
      [`/{bucket}`],
      [Create bucket],
    [Head],
      [`/{bucket}/{key}`],
      [Retrieve object metadata],
    [Get],
      [`/bucket}/{*key}`],
      [Retrieve an object (with decryption and column filtering for Parquet)],
    [Put],
      [`/{bucket}/{*key}`],
      [Store an object (with encryption for Parquet)],
  ),
)<tab:s3-compatible-endpoints>

