#import "cmds.typ": todo, delete, maybeDelete, update

= Methodology

As

== Benchmarking

#delete[Since the OSWS will act as a wrapper for the real S3, it is essential to measure the baseline overhead of the OSWS.

For this #link("https://github.com/minio/warp")[Warp] by #link("https://www.min.io/")[MinIO] will be used.
MinIO previously provided the OSS #link("https://github.com/minio/minio")[MinIO], a S3-compatible object store.
MinIO's services are used by multiple Fortune 500 companies, such as Apple and Intel.@using_minio_landbase@using_minio_theirstack
Their benchmark is chosen because it is specifically designed to benchmark S3-compatible systems, and they themselves and #link("https://github.com/seaweedfs/seaweedfs#run-warp-and-launch-a-mixed-benchmark")[SeaweedFS] use it to benchmark their systems.
Warp is also used within academia, e.g. in "Performance analysis of mdx II: A next-generation cloud platform for cross-disciplinary data science research"@takahashi2025performanceanalysismdxii
A large community also supports Warp; it has 39 contributors and 767 stars on GitHub and is on the stable 1.4.1 release, as of the day of writing.#footnote[Written 2026/04/14].
Alternatives such as #link("https://github.com/intel-cloud/cosbench")[COSBench] and #link("https://github.com/igneous-systems/s3bench")[S3Bench] are either in pre-release or archived, and thus were not chosen.
Other benchmarks also exist, but they are usually designed, e.g. OLAP and OLTP, and are therefore not representative of data lakes' workloads.
Warp will then be run directly against S3, against OSWS with cryptographic operations skipped, against OSWS with encryption but without caching, and against OSWS with encryption and with caching.
This will allow comparison between the basic overhead OSWS might add, but also enable a general comparison between other systems, which ensures access control by encryption.
To see if OSWS scales, it is necessary to test with multiple instances.
This will be done by running the benchmark with the following varying number of instances: one, two, four, and eight.
#update[Since it was run on personal computers, it was limited to eight cores, as the computers were limited to 12 cores in total, and 6 of them were performance cores, and therefore, the rest of the cores were used by other background tasks.
See @fig:hardware-specs for hardware specifications.]
The benchmark configurations will result in insight into whether the different setups of OSWS are inherently worse, in terms of performance, or if they might provide an optimization, e.g. by using caching for the keys and Parquet files.] // DELETE TO HERE

As OSWS inherently implements different design choices compared to S3, no standardized benchmarking has been chosen, such as #link("https://github.com/minio/warp")[Warp] which is otherwise used by multiple other Fortune 500 companies.@using_minio_landbase@using_minio_theirstack
The reasoning for this is that OSWS implements its own caching layer and uses a KV, and as such, the benchmark would have to ensure that it tests both the throughput of N instances of OSWS running and that the configuration of caching and encryption is changed out.
OSWS also does encryption per column, and therefore, the sizes of the Parquet files have a lot of significance for the end throughput, and Warp does not vary its Parquet file size.
This results in inherently different throughputs and numbers, which are hard to compare OSWS against anything else.
Thus, the choice was to set up the following E2E benchmarks.
Three Parquet files will be auto-generated by a script.
These will have the following sizes:

- _Parquet Size 1:_\~100MB Parquet file with 2,000 columns and 5,000 rows
- _Parquet Size 2:_\~200MB Parquet file with 2,000 columns and 10,000 rows
- _Parquet Size 3:_\~2GB Parquet file with 2,000 columns and 100,000 rows

Python scripts will then run puts and gets against the following setups:

- Directly against S3 (we used R2)
- Against OSWS with encryption and with caching
- Against OSWS with encryption and no caching
- Against OSWS with no encryption and no caching

The metric for this will be latency, and for each run, #todo[N files] will be run through twice, allowing comparison of how slow or fast OSWS is when there is no cache hit and when the cache is hit.

Given the results, the individual parts of the OSWS can be analyzed to identify which part might be the largest contributor to overhead.
The following tiny benchmarks will be measured:

- *Permissions:* How long it takes to authorize the user's access to a column.\
  This itself has two stages.\
  _Stage 1_ is to check if changing the depth of the connected roles (the depth) has an influence.
  This will be done for a hierarchy of depth 0, 4, 16, and 64 roles interconnected.\
  _Stage 2_ is to check if changing the overall number of roles in the system (with a flat hierarchy) has any influence.
  This will be done for 4, 64, and 256 roles.
  Should be done for an RBAC system with four roles: 64 and 256.
- *Unwrapping:* How long it takes to unwrap a key.\
  Should be done for key sizes of 128 and 256 bits.
  This 
- *Decryption:* How long it takes to decrypt a column.\
  This will, as well as E2E benchmark, be done for _Parquet Size 1_, _Parquet Size 2_, and _Parquet Size 3_.\
  The encryption algorithm used within Parquet Sharp is AES.

See @tab:todo-benchmarks for an overview of the benchmarks and their configurations, which will be run.

#include "5-methodology/benchmark-config.typ"

=== Testing

As one of the goals of the OSWS was to enable all query engines and managed all-in-one platforms to use it, a few tests are needed.

One query engine and ...
// I den rigtige rapport skal vi nok inkludere præcise definitioner af setuppet her; hvad er det for en query engine? i hvilket setup? og hvad for en "fully managed data lake platform" (plus måske også definere hvad vi mener med det). Desuden er det vigtigt at specificere at det vi mener er at en fully managed data lake platform's QUERY ENGINE skal kunne bruge os, hvilket kræver at de supporter det (fx Snowflakes external tables)
Both should be able to put and get files (given sufficient permissions) as they normally do.
Depending on how they read the data, some modifications might be needed as the columns might still be encrypted, which will result in an error, but this cannot be addressed without changing the actual schema in the OSWS.
