#import "cmds.typ": todo, delete, maybeDelete, update, new

= Methodology
<sec:methodology>

To ensure OSWS could live up to the intended use-cases and to check the viability of it, both benchmarking and e2e (end-to-end) tests are needed.
This section will cover both the setup of the benchmark and the setup of the e2e test.

All source code is available at~#link("https://github.com/lucasfth/osws")[github.com/lucasfth/osws], and also describes how to get it running.
The version used for testing and benchmarking was `V2026.0.0 Alpha`#footnote[ https://github.com/lucasfth/osws/releases/tag/V2026.0.0-alpha]

== E2E Tests

As one of the goals of the OSWS was to enable third-party query engines to connect without any modification, a test confirming this behaviour is needed.

An e2e test will be created that asserts different query engines can connect and perform queries as normal, with OSWS providing column-level security based on the test user's roles.
The e2e test suite will contain a seeding step that sets up the necessary users and roles.
Python scripts will be used to orchestrate setting up roles and permissions, and asserting that the fetched data does not contain unauthorized data.
The test will use the "Titanic" sample dataset #footnote(link("https://www.agentsfordata.com/app?sample-id=titanic&tab=local")) and permissions will be configured so three different roles have limited access, but to different columns.
One role will inherit from all roles and have direct access to all other columns, thus having full access.
This will then test the role hierarchy feature.
Then, the following will be used to fetch the Parquet file through different users and assert that only the permitted columns are viewable:

/ Python script: A Python script using an S3 client like `boto3`#footnote[https://github.com/boto/boto3] and a Parquet reader like `pyarrow`#footnote[https://github.com/apache/arrow] to fetch a file from OSWS.

/ DuckDB: A DuckDB instance will query the parquet file through OSWS.

/ Apache Spark: An Apache Spark instance (through PySpark) will query the parquet file through OSWS.

Each of the different tools should assert that only the permitted data is viewable.

== Benchmarking

All benchmarking of OSWS was run on a Digital Ocean VM with access to 8 cores and $16$GB of DRAM, see~@app:vm-spec for full specification overview, together with Digital Ocean's own Object Store (Spaces), which is S3-compatible.
For benchmarks using a key vault, Azure KV was used.
All services were kept in the same region to further ensure minimal network latency.
The test Parquet files used in the following benchmarks can be defined as follows:

- _Parquet Size Tiny:_$\~500$KB Parquet file with 50 columns and 1,000 rows.
- _Parquet Size Small:_$\~5$MB Parquet file with 50 columns and 10,000 rows.
- _Parquet Size Medium:_$\~125$MB Parquet file with 50 columns and 250,000 rows.
- _Parquet Size Large:_$\~500$MB Parquet file with 50 columns and 1,000,000 rows.
- _Parquet Size X-Large:_$\~1$GB Parquet file with 50 columns and 2,000,000 rows.

The five Parquet files are auto-generated by a script that is also available in the source code.
The configuration of the files was chosen to reflect a somewhat realistic distribution of different sizes of Parquet files.
Various openly available datasets were compared to settle on the choice of 50 columns.
For example, several real-world example datasets used for benchmarking, available from the cloud analytics platform ClickHouse, contain fewer than 50 columns.~@clickhouse-datasets
Another is a dataset collecting 1.1 billion taxi and Uber rides in New York City, which contains 51 columns.~@uber-taxi
50 columns seemed like a realistic number of columns for a large OLAP dataset and was thus used for the sizes.

=== Micro Benchmarks

The micro benchmarks that will be run will show how each major part of OSWS performs to get insights into how much they add to latency.
The following micro-benchmarks will be run:

+ Permission Service
+ Permission Hierarchy
+ Unwrapping
+ Decryption

_Permission Service_ will measure the latency of how long it takes to get a user's effective roles to the given columns, when there are no inherited roles, i.e. the role hierarchy is flat.
The columns stay at a constant 50, the roles assigned to the user are varied from 4, 64, and 256 roles, and they are each assigned, on average, access to 80% of each of the columns.

_Permission Hierarchy_ will measure the latency of how long it takes to get a user's effective roles, now with the role hierarchy introduced.
The number of roles assigned is constantly at one, while the number of inherited roles assigned varies from 0, 4, 16, and 64 and again, on average, each role is assigned access to 80% of the columns.

_Unwrapping_ will measure the e2e latency for reading a tiny Parquet file (the small Parquet files are also run but ignored, but can be seen in~@app:micro) with a cold cache.
The varying key sizes of 128, 192, and 256 bits will primarily affect the symmetric AES-GCM decryption.

_Decryption_ will measure the latency for reading and decrypting a Parquet file, and the keys for decrypting will have been warmed and thus stored in cache; thus, KV is not taken into account here.
The Parquet sizes that will be used are the same as with e2e benchmarking, being the tiny, small, medium, large, and extra large.

All of the micro-benchmarks were run 15 times to obtain statistically meaningful results.

#include "5-methodology/benchmark-config.typ"

=== E2E Benchmarks

The micro benchmarks show the individual parts' contribution to latency, but the overall performance of OSWS is more important to identify if, from a performance perspective, OSWS is usable within production environments.

As OSWS inherently implements different design choices compared to plain S3, no standardized benchmarking has been chosen, such as Warp#footnote[https://github.com/minio/warp], which is otherwise used by multiple other Fortune 500 companies.~@using_minio_landbase@using_minio_theirstack
The reasoning for this is that OSWS implements its own caching layer and uses a KV; as such, the benchmark would have to ensure that it tests both the throughput of N instances of OSWS running and that the configuration of caching and encryption is considered thoroughly.

OSWS also encrypts each column, resulting in the sizes of the Parquet files having a lot of significance for the end throughput, and Warp does not vary its Parquet file size.
This results in inherently different throughputs and numbers, which are hard to compare OSWS against anything else.

Lastly, OSWS, as mentioned, in~@sec:sys-design:decryption, does not use proper range requests when it queries the Object Store, instead always fetching the full file and slicing after.
As a result, it will obviously perform worse for ranged requests compared to direct S3 ones.#footnote[A solution to this is proposed within~@sec:discussion.]

Python scripts will then run Parquet PUTs and GETs against the following setups:

- Directly against an S3-compatible store, in this case Digital Ocean Spaces
- Against OSWS with encryption and with caching
- Against OSWS with encryption and no file cache
- Against OSWS with encryption and no DEK cache
- Against OSWS with no encryption and no caching

The metric for this will be end-to-end latency, and for each file, the benchmark will be run for a total of 10 times, both cold and warm, allowing comparison of how slow or speed differences occur with and without caches.
As soon as a Parquet file has been fetched once and a DEK has been unwrapped once, they will be warm, and thus in cache.

See~@tab:todo-benchmarks for an overview of all benchmarks and their configurations, which will be run.