#import "@preview/lilaq:0.6.0" as lq

// Generated by generate-thesis-plots.py
// GET (warm) latency by file size
#figure(
  lq.diagram(
    width: 10cm,
    title: [GET (warm) latency by file size],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]), (4, [large]))),
    ylabel: [Latency (ms)],
    yscale: "log",
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (11.15, 32.69, 489.84, 1915.01),
    mark: "o",
    label: [S3 Direct],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (29.18, 81.64, 1616.59, 6097.30),
    mark: "s",
    label: [OSWS],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (34.42, 129.18, 2281.57, 9024.56),
    mark: "^",
    label: [No file cache],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (35.54, 132.89, 1302.23, 5103.12),
    mark: "x",
    label: [No encryption],
  ),
  ),
  caption: [Median GET latency with warm cache. S3 Direct is the baseline. OSWS adds encryption and RBAC overhead; \"No file cache\" forces re-decryption on every request.],
)

// GET latency: warm vs cold (OSWS, encrypt+cache)
#figure(
  lq.diagram(
    width: 10cm,
    title: [GET latency: warm vs cold (OSWS, encrypt+cache)],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]), (4, [large]))),
    ylabel: [Latency (ms)],
    yscale: "log",
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (29.18, 81.64, 1616.59, 6097.30),
    mark: "o",
    label: [Warm (DEK cached)],
  ),
  lq.plot(
    (1.00, 2.00, 3.00, 4.00),
    (3558.46, 3702.97, 6024.01, 13230.02),
    mark: "s",
    label: [Cold (DEK cache miss)],
  ),
  ),
  caption: [Cold GET forces a Key Vault round-trip for each of the 50 column DEKs. The gap between the two lines represents the DEK cache savings.],
)

// DEK cache impact on GET latency
#figure(
  lq.diagram(
    width: 10cm,
    title: [DEK cache impact on GET latency],
    xaxis: (ticks: ((1, [tiny]), (2, [small]), (3, [medium]))),
    ylabel: [Latency (ms)],
    yscale: "log",
  lq.plot(
    (1.00, 2.00, 3.00),
    (29.18, 81.64, 1616.59),
    mark: "o",
    label: [DEK cache enabled],
  ),
  lq.plot(
    (1.00, 2.00, 3.00),
    (14635.89, 15361.68, 76457.60),
    mark: "s",
    label: [DEK cache disabled],
  ),
  ),
  caption: [Warm GET with and without the DEK cache (tiny--medium only; the large benchmark timed out on 9/10 runs without DEK caching). Without caching, every GET requires one Key Vault call per column.],
)
